services:
  POSTGRES:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DATABASE=cadastro_banco
      - POSTGRES_ROOT_PASSWORD=root
    volumes:
      - cadastro_pg_data:/bitnami/postgresql
volumes:
  cadastro_pg_data: